
// Suppliers added for the products sourced from electrical_items.xlsx.
// `productCount` and `totalPurchases` are computed from the workbook.
  {
    id: "s6",
    name: "ElectroMart Kenya",
    contactPerson: "John Mwangi",
    phone: "+254 711 600 100",
    email: "sales@electromart.co.ke",
    address: "Industrial Area, Nairobi",
    productCount: 21,
    totalPurchases: 25950,
  },
  {
    id: "s7",
    name: "AgriTools Suppliers",
    contactPerson: "Mary Akinyi",
    phone: "+254 722 700 200",
    email: "orders@agritools.co.ke",
    address: "Kitengela, Kajiado",
    productCount: 26,
    totalPurchases: 41990,
  },
  {
    id: "s8",
    name: "ColorHub Distributors",
    contactPerson: "Peter Njoroge",
    phone: "+254 733 800 300",
    email: "info@colorhub.co.ke",
    address: "Mombasa Road, Nairobi",
    productCount: 12,
    totalPurchases: 20740,
  },
  {
    id: "s9",
    name: "AquaPro Sanitary Supplies",
    contactPerson: "Susan Wambui",
    phone: "+254 700 900 400",
    email: "sales@aquapro.co.ke",
    address: "Westlands, Nairobi",
    productCount: 29,
    totalPurchases: 83910,
  },
  {
    id: "s10",
    name: "BuildMart Hardware",
    contactPerson: "Daniel Otieno",
    phone: "+254 720 100 500",
    email: "info@buildmart.co.ke",
    address: "Kenyatta Avenue, Nairobi",
    productCount: 15,
    totalPurchases: 17900,
  },
  {
    id: "s11",
    name: "Precision Tools Ltd",
    contactPerson: "Joyce Chebet",
    phone: "+254 711 200 600",
    email: "sales@precisiontools.co.ke",
    address: "Parklands, Nairobi",
    productCount: 48,
    totalPurchases: 76110,
  },
  {
    id: "s12",
    name: "SecureLock Fittings",
    contactPerson: "Brian Kiprop",
    phone: "+254 722 300 700",
    email: "orders@securelock.co.ke",
    address: "Thika Road, Ruiru",
    productCount: 11,
    totalPurchases: 22530,
  },
  {
    id: "s13",
    name: "FastRight Hardware",
    contactPerson: "Esther Nyambura",
    phone: "+254 733 400 800",
    email: "sales@fastright.co.ke",
    address: "Eastleigh, Nairobi",
    productCount: 7,
    totalPurchases: 3780,
  },
  {
    id: "s14",
    name: "Rope & Cord Wholesalers",
    contactPerson: "Kevin Mutiso",
    phone: "+254 700 500 900",
    email: "info@ropecord.co.ke",
    address: "Gikomba, Nairobi",
    productCount: 8,
    totalPurchases: 6110,
  },
  {
    id: "s15",
    name: "PipeWorks Kenya",
    contactPerson: "Linet Achieng",
    phone: "+254 720 600 100",
    email: "sales@pipeworks.co.ke",
    address: "Kasarani, Nairobi",
    productCount: 42,
    totalPurchases: 62310,
  },
  {
    id: "s16",
    name: "MasonPro Supplies",
    contactPerson: "Anthony Karanja",
    phone: "+254 711 700 200",
    email: "orders@masonpro.co.ke",
    address: "Ngong Road, Nairobi",
    productCount: 11,
    totalPurchases: 13800,
  },
  {
    id: "s17",
    name: "FixIt Fasteners",
    contactPerson: "Caroline Wairimu",
    phone: "+254 722 800 300",
    email: "info@fixit.co.ke",
    address: "Mombasa Road, Athi River",
    productCount: 3,
    totalPurchases: 1730,
  },
  {
    id: "s18",
    name: "SealRight Chemicals",
    contactPerson: "George Maina",
    phone: "+254 733 900 400",
    email: "sales@sealright.co.ke",
    address: "Industrial Area, Nairobi",
    productCount: 8,
    totalPurchases: 18270,
  },
  {
    id: "s19",
    name: "HomeFix Distributors",
    contactPerson: "Faith Wangari",
    phone: "+254 700 100 500",
    email: "orders@homefix.co.ke",
    address: "Yaya Centre, Nairobi",
    productCount: 6,
    totalPurchases: 16760,
  },
  {
    id: "s20",
    name: "BuildChem Supplies",
    contactPerson: "Stephen Ouma",
    phone: "+254 720 200 600",
    email: "sales@buildchem.co.ke",
    address: "Mlolongo, Machakos",
    productCount: 3,
    totalPurchases: 800,
  },
  {
    id: "s21",
    name: "HingeRight Hardware",
    contactPerson: "Rebecca Atieno",
    phone: "+254 711 300 700",
    email: "info@hingeright.co.ke",
    address: "Kirinyaga Road, Nairobi",
    productCount: 8,
    totalPurchases: 6190,
  },
  {
    id: "s22",
    name: "AutoBike Parts Kenya",
    contactPerson: "Joseph Wekesa",
    phone: "+254 722 400 800",
    email: "sales@autobike.co.ke",
    address: "Likoni Road, Nairobi",
    productCount: 11,
    totalPurchases: 17250,
  },
  {
    id: "s23",
    name: "SafeGuard PPE",
    contactPerson: "Margaret Naliaka",
    phone: "+254 733 500 900",
    email: "orders@safeguard.co.ke",
    address: "Enterprise Road, Nairobi",
    productCount: 1,
    totalPurchases: 1000,
  },

// Products imported from frontend/electrical_items.xlsx. Each row in each
// sheet becomes a product entry. `buyingPrice` is ESTIMATED at 75% of the
// selling price (the sheet only has selling prices) — go back and correct
// it per product once you know your real supplier cost. Codes use the same
// prefix scheme as seed-products.ts.

// Append imported products (caller will splice this into the products array).
export const importedProducts: Product[] = [
  {
    id: "i0001",
    name: "Lampholder",
    code: "ELE-0001",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 9,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0002",
    name: "Plugs",
    code: "ELE-0002",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0003",
    name: "Double pole switch",
    code: "ELE-0003",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0004",
    name: "Socket double 2 gang",
    code: "ELE-0004",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0005",
    name: "Switch 1 gang 2 way",
    code: "ELE-0005",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 18,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0006",
    name: "Single socket",
    code: "ELE-0006",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 15,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0007",
    name: "Cable clips 12mm (packet)",
    code: "ELE-0007",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 98,
    sellingPrice: 130,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0008",
    name: "Cable clips 9mm (packet)",
    code: "ELE-0008",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 83,
    sellingPrice: 110,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0009",
    name: "Cable clips 10mm (packet)",
    code: "ELE-0009",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0010",
    name: "Bulb 9W",
    code: "ELE-0010",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 9,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0011",
    name: "Bulb 5W",
    code: "ELE-0011",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0012",
    name: "Bulb 7W",
    code: "ELE-0012",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0013",
    name: "Black tape",
    code: "ELE-0013",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 46,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0014",
    name: "White tape",
    code: "ELE-0014",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 28,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0015",
    name: "Single switch box (white)",
    code: "ELE-0015",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 21,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0016",
    name: "Double switch box (white)",
    code: "ELE-0016",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 39,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0017",
    name: "Single switch box (black)",
    code: "ELE-0017",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 80,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0018",
    name: "Double switch box (black)",
    code: "ELE-0018",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 27,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0019",
    name: "Junction box (black)",
    code: "ELE-0019",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 20,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0020",
    name: "Electric coil",
    code: "ELE-0020",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 195,
    sellingPrice: 260,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0021",
    name: "Voltage tester",
    code: "ELE-0021",
    category: "Electrical Items",
    description: "",
    supplierId: "s6",
    supplierName: "ElectroMart Kenya",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 39,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0022",
    name: "Rake head only",
    code: "GAR-0001",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 210,
    sellingPrice: 280,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0023",
    name: "Rake (full, with handle)",
    code: "GAR-0002",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 338,
    sellingPrice: 450,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0024",
    name: "Pickaxe head",
    code: "GAR-0003",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 488,
    sellingPrice: 650,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0025",
    name: "Panga - Alligator",
    code: "GAR-0004",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0026",
    name: "Panga - Knicker big",
    code: "GAR-0005",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0027",
    name: "Panga - Knicker small",
    code: "GAR-0006",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0028",
    name: "Slasher",
    code: "GAR-0007",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 210,
    sellingPrice: 280,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0029",
    name: "Fork jembe head (type 1)",
    code: "GAR-0008",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 413,
    sellingPrice: 550,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0030",
    name: "Fork jembe head (type 2)",
    code: "GAR-0009",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 488,
    sellingPrice: 650,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0031",
    name: "Jembe head",
    code: "GAR-0010",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0032",
    name: "Fencing shear - wood handle",
    code: "GAR-0011",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0033",
    name: "Fencing shear - plastic handle",
    code: "GAR-0012",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0034",
    name: "Hack saw",
    code: "GAR-0013",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 9,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0035",
    name: "Handsaw wood 24 inch",
    code: "GAR-0014",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0036",
    name: "Handsaw wood 16 inch",
    code: "GAR-0015",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0037",
    name: "Handsaw wood 20 inch",
    code: "GAR-0016",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0038",
    name: "Curved pruning saw",
    code: "GAR-0017",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0039",
    name: "Hammer - rubber handle",
    code: "GAR-0018",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0040",
    name: "Hammer - juakali",
    code: "GAR-0019",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 9,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0041",
    name: "Hammer - rubber handle (1200)",
    code: "GAR-0020",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 900,
    sellingPrice: 1200,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0042",
    name: "Spade",
    code: "GAR-0021",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 413,
    sellingPrice: 550,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0043",
    name: "Sprayer",
    code: "GAR-0022",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 1350,
    sellingPrice: 1800,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0044",
    name: "Other saw",
    code: "GAR-0023",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 248,
    sellingPrice: 330,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0045",
    name: "Axe head",
    code: "GAR-0024",
    category: "Garden Tools",
    description: "",
    supplierId: "s7",
    supplierName: "AgriTools Suppliers",
    buyingPrice: 600,
    sellingPrice: 800,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0046",
    name: "Paint brush 5 inch",
    code: "PTM-0001",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 27,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0047",
    name: "Paint brush 2 inch",
    code: "PTM-0002",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 19,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0048",
    name: "Paint brush 4 inch",
    code: "PTM-0003",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 9,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0049",
    name: "Paint brush 3 inch",
    code: "PTM-0004",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 26,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0050",
    name: "Paint brush 6 inch",
    code: "PTM-0005",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 128,
    sellingPrice: 170,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0051",
    name: "Paint brush 3/4 inch",
    code: "PTM-0006",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0052",
    name: "Paint brush 25mm",
    code: "PTM-0007",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0053",
    name: "Paint roller",
    code: "PTM-0008",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0054",
    name: "Thinner 1 litre (brand A)",
    code: "PTM-0009",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0055",
    name: "Thinner 1 litre (brand B)",
    code: "PTM-0010",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 195,
    sellingPrice: 260,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0056",
    name: "Turpentine 500ml",
    code: "PTM-0011",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 165,
    sellingPrice: 220,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0057",
    name: "Turpentine 1 litre",
    code: "PTM-0012",
    category: "Painting Tools & Materials",
    description: "",
    supplierId: "s8",
    supplierName: "ColorHub Distributors",
    buyingPrice: 300,
    sellingPrice: 400,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0058",
    name: "Flush handle - light gauge",
    code: "BAT-0001",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 20,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0059",
    name: "Flush handle - heavy gauge",
    code: "BAT-0002",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0060",
    name: "Wall tap - star handle",
    code: "BAT-0003",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 488,
    sellingPrice: 650,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0061",
    name: "Top flush plastic cistern",
    code: "BAT-0004",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 1125,
    sellingPrice: 1500,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0062",
    name: "High level flush",
    code: "BAT-0005",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 1125,
    sellingPrice: 1500,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0063",
    name: "Water tank float valve - Lirlee",
    code: "BAT-0006",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 488,
    sellingPrice: 650,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0064",
    name: "Water tank float valve - Peckler",
    code: "BAT-0007",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 525,
    sellingPrice: 700,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0065",
    name: "Toilet pan",
    code: "BAT-0008",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 2175,
    sellingPrice: 2900,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0066",
    name: "Toilet bowl",
    code: "BAT-0009",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 2625,
    sellingPrice: 3500,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0067",
    name: "Toilet pump - big",
    code: "BAT-0010",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 105,
    sellingPrice: 140,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0068",
    name: "Toilet pump - small",
    code: "BAT-0011",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0069",
    name: "Shower head",
    code: "BAT-0012",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 19,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0070",
    name: "Toilet seat cover",
    code: "BAT-0013",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 450,
    sellingPrice: 600,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0071",
    name: "Syphon cistern",
    code: "BAT-0014",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 15,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0072",
    name: "Plastic cistern fitting",
    code: "BAT-0015",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 450,
    sellingPrice: 600,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0073",
    name: "Water tap - Pegler",
    code: "BAT-0016",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0074",
    name: "Water tap - Lirlee",
    code: "BAT-0017",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 300,
    sellingPrice: 400,
    stock: 21,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0075",
    name: "Brass gate valve - Lirlee",
    code: "BAT-0018",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0076",
    name: "Brass gate valve - Pegler",
    code: "BAT-0019",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 450,
    sellingPrice: 600,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0077",
    name: "Brass ball valve - Lirlee",
    code: "BAT-0020",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0078",
    name: "Cartoon lockable tap",
    code: "BAT-0021",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0079",
    name: "Plastic tap",
    code: "BAT-0022",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 24,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0080",
    name: "PPR gate valve",
    code: "BAT-0023",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0081",
    name: "Wall tap",
    code: "BAT-0024",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 488,
    sellingPrice: 650,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0082",
    name: "Ball valve - cistern",
    code: "BAT-0025",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0083",
    name: "Sink - single medium",
    code: "BAT-0026",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 1125,
    sellingPrice: 1500,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0084",
    name: "Sink - single one hole",
    code: "BAT-0027",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0085",
    name: "Sink - light heavy",
    code: "BAT-0028",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 2250,
    sellingPrice: 3000,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0086",
    name: "Sink - double hole",
    code: "BAT-0029",
    category: "Bathroom & Toiletry",
    description: "",
    supplierId: "s9",
    supplierName: "AquaPro Sanitary Supplies",
    buyingPrice: 3375,
    sellingPrice: 4500,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0087",
    name: "Plumb bob",
    code: "GHW-0001",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 21,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0088",
    name: "Chair pins (pack)",
    code: "GHW-0002",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0089",
    name: "Open screw hook (pack)",
    code: "GHW-0003",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0090",
    name: "Padlock 25mm",
    code: "GHW-0004",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0091",
    name: "Padlock 32mm",
    code: "GHW-0005",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 14,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0092",
    name: "Padlock 38mm",
    code: "GHW-0006",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 13,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0093",
    name: "Padlock 50mm",
    code: "GHW-0007",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0094",
    name: "Padlock 63mm",
    code: "GHW-0008",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0095",
    name: "Concrete nails 1 inch (pack)",
    code: "GHW-0009",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0096",
    name: "Concrete nails 1.5 inch (pack)",
    code: "GHW-0010",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0097",
    name: "Concrete nails 2 inch (pack)",
    code: "GHW-0011",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0098",
    name: "Concrete nails 2.5 inch (pack)",
    code: "GHW-0012",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0099",
    name: "Concrete nails 3 inch (pack)",
    code: "GHW-0013",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0100",
    name: "Concrete nails 4 inch (pack)",
    code: "GHW-0014",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0101",
    name: "Lubricating oil",
    code: "GHW-0015",
    category: "General Hardware",
    description: "",
    supplierId: "s10",
    supplierName: "BuildMart Hardware",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 14,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0102",
    name: "File (150 type)",
    code: "HTM-0001",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0103",
    name: "File (120 type)",
    code: "HTM-0002",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0104",
    name: "Steel trowel (price not provided)",
    code: "HTM-0003",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 0,
    sellingPrice: 0,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0105",
    name: "Try square (type 1)",
    code: "HTM-0004",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0106",
    name: "Try square (type 2)",
    code: "HTM-0005",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0107",
    name: "Try square (type 3)",
    code: "HTM-0006",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0108",
    name: "Tape measure 5m - Knicker brand",
    code: "HTM-0007",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 19,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0109",
    name: "Tape measure 5m - Kenyos brand",
    code: "HTM-0008",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 83,
    sellingPrice: 110,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0110",
    name: "Tape measure 3m - Knicker brand",
    code: "HTM-0009",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 68,
    sellingPrice: 90,
    stock: 15,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0111",
    name: "Tape measure 7.5m - Knicker brand",
    code: "HTM-0010",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0112",
    name: "Tape measure 3m - Bsmtis brand",
    code: "HTM-0011",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 68,
    sellingPrice: 90,
    stock: 23,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0113",
    name: "Adjustable spanner 8 inch",
    code: "HTM-0012",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 338,
    sellingPrice: 450,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0114",
    name: "Adjustable spanner 10 inch",
    code: "HTM-0013",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 450,
    sellingPrice: 600,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0115",
    name: "Adjustable spanner 12 inch",
    code: "HTM-0014",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 525,
    sellingPrice: 700,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0116",
    name: "Adjustable spanner 14 inch",
    code: "HTM-0015",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 600,
    sellingPrice: 800,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0117",
    name: "Wire brush",
    code: "HTM-0016",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0118",
    name: "Ring spanner 14x15 - chrome",
    code: "HTM-0017",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 135,
    sellingPrice: 180,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0119",
    name: "Ring spanner 14x15 - normal",
    code: "HTM-0018",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 26,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0120",
    name: "Ring spanner 12x13 - normal",
    code: "HTM-0019",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 105,
    sellingPrice: 140,
    stock: 17,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0121",
    name: "Open end spanner 10x11 - chrome",
    code: "HTM-0020",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 105,
    sellingPrice: 140,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0122",
    name: "Open end spanner 25x28 - normal",
    code: "HTM-0021",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 9,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0123",
    name: "Single ring/open end spanner 14x14 - chrome",
    code: "HTM-0022",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 135,
    sellingPrice: 180,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0124",
    name: "Pliers - Knicker (Ksh 220 type)",
    code: "HTM-0023",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 165,
    sellingPrice: 220,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0125",
    name: "Pliers - Knicker (Ksh 250 type)",
    code: "HTM-0024",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0126",
    name: "Combination pliers - big",
    code: "HTM-0025",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 24,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0127",
    name: "Combination pliers - small",
    code: "HTM-0026",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 135,
    sellingPrice: 180,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0128",
    name: "Pliers 6 inch - Fuxiang",
    code: "HTM-0027",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0129",
    name: "Pliers 8 inch - Fuxiang",
    code: "HTM-0028",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0130",
    name: "Pliers - Intco",
    code: "HTM-0029",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 210,
    sellingPrice: 280,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0131",
    name: "Hammer - small (Ksh 250 type)",
    code: "HTM-0030",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0132",
    name: "Hammer (Ksh 500 type) - new stock",
    code: "HTM-0031",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0133",
    name: "Hammer (Ksh 1200 type) - new stock",
    code: "HTM-0032",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 900,
    sellingPrice: 1200,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0134",
    name: "Hammer - juakali - new stock",
    code: "HTM-0033",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0135",
    name: "Screwdriver - Mosi",
    code: "HTM-0034",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0136",
    name: "Screwdriver - Goodmate",
    code: "HTM-0035",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0137",
    name: "Screwdriver - Exclusive",
    code: "HTM-0036",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0138",
    name: "Screwdriver - Intco",
    code: "HTM-0037",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0139",
    name: "Tile cutter",
    code: "HTM-0038",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0140",
    name: "Iron jack plane",
    code: "HTM-0039",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 450,
    sellingPrice: 600,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0141",
    name: "Screwdriver - fine durable",
    code: "HTM-0040",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0142",
    name: "Screwdriver - Baku",
    code: "HTM-0041",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0143",
    name: "Spirit level (Ksh 200 type)",
    code: "HTM-0042",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 17,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0144",
    name: "Spirit level (Ksh 170 type)",
    code: "HTM-0043",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 128,
    sellingPrice: 170,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0145",
    name: "Spirit level (Ksh 220 type)",
    code: "HTM-0044",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 165,
    sellingPrice: 220,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0146",
    name: "Chisel scraper",
    code: "HTM-0045",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 20,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0147",
    name: "Tag hammer",
    code: "HTM-0046",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 300,
    sellingPrice: 400,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0148",
    name: "Stainless steel trowel - Knicker (Ksh 150 type)",
    code: "HTM-0047",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0149",
    name: "Stainless steel trowel - Knicker (Ksh 120 type)",
    code: "HTM-0048",
    category: "Hand Tools & Measuring",
    description: "",
    supplierId: "s11",
    supplierName: "Precision Tools Ltd",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0150",
    name: "Window stay",
    code: "WLF-0001",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0151",
    name: "Window fastener",
    code: "WLF-0002",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 56,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0152",
    name: "Lock bolt - new",
    code: "WLF-0003",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0153",
    name: "Lock bolt - juakali",
    code: "WLF-0004",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 14,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0154",
    name: "Tower bolt",
    code: "WLF-0005",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 60,
    sellingPrice: 80,
    stock: 22,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0155",
    name: "Lock bolt juakali (Ksh 120 type)",
    code: "WLF-0006",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 90,
    sellingPrice: 120,
    stock: 37,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0156",
    name: "Lock bolt juakali (Ksh 210 type)",
    code: "WLF-0007",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 158,
    sellingPrice: 210,
    stock: 15,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0157",
    name: "Lock bolt juakali (Ksh 100 type)",
    code: "WLF-0008",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 13,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0158",
    name: "Lock bolt juakali (Ksh 50 type)",
    code: "WLF-0009",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 25,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0159",
    name: "Bed nuts",
    code: "WLF-0010",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 19,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0160",
    name: "Bed nuts - juakali",
    code: "WLF-0011",
    category: "Window & Lock Fittings",
    description: "",
    supplierId: "s12",
    supplierName: "SecureLock Fittings",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0161",
    name: "MDF screws 25mm (pack)",
    code: "SCF-0001",
    category: "Screws & Fasteners",
    description: "",
    supplierId: "s13",
    supplierName: "FastRight Hardware",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0162",
    name: "Gypsum screws 40mm (pack)",
    code: "SCF-0002",
    category: "Screws & Fasteners",
    description: "",
    supplierId: "s13",
    supplierName: "FastRight Hardware",
    buyingPrice: 210,
    sellingPrice: 280,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0163",
    name: "Wood screw 3 inch (packet)",
    code: "SCF-0003",
    category: "Screws & Fasteners",
    description: "",
    supplierId: "s13",
    supplierName: "FastRight Hardware",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0164",
    name: "Wood screw 1.5 inch (packet)",
    code: "SCF-0004",
    category: "Screws & Fasteners",
    description: "",
    supplierId: "s13",
    supplierName: "FastRight Hardware",
    buyingPrice: 135,
    sellingPrice: 180,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0165",
    name: "Star screw (Ksh 220 type)",
    code: "SCF-0005",
    category: "Screws & Fasteners",
    description: "",
    supplierId: "s13",
    supplierName: "FastRight Hardware",
    buyingPrice: 165,
    sellingPrice: 220,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0166",
    name: "Star screw (Ksh 70 type)",
    code: "SCF-0006",
    category: "Screws & Fasteners",
    description: "",
    supplierId: "s13",
    supplierName: "FastRight Hardware",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0167",
    name: "Flat screw",
    code: "SCF-0007",
    category: "Screws & Fasteners",
    description: "",
    supplierId: "s13",
    supplierName: "FastRight Hardware",
    buyingPrice: 19,
    sellingPrice: 25,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0168",
    name: "Rope (general)",
    code: "ROP-0001",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0169",
    name: "Rope 8x10",
    code: "ROP-0002",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 135,
    sellingPrice: 180,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0170",
    name: "Rope 10x10",
    code: "ROP-0003",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0171",
    name: "Rope 9x10",
    code: "ROP-0004",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 165,
    sellingPrice: 220,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0172",
    name: "Rope 7x10",
    code: "ROP-0005",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 98,
    sellingPrice: 130,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0173",
    name: "Rope 6x10",
    code: "ROP-0006",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 83,
    sellingPrice: 110,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0174",
    name: "Rope (many colors) 42ply",
    code: "ROP-0007",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 19,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0175",
    name: "Rope (many colors) 16ply",
    code: "ROP-0008",
    category: "Ropes",
    description: "",
    supplierId: "s14",
    supplierName: "Rope & Cord Wholesalers",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 13,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0176",
    name: "Waste gully trap",
    code: "PLP-0001",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0177",
    name: "Connection tubes",
    code: "PLP-0002",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0178",
    name: "PVC fitting and piping 100ml",
    code: "PLP-0003",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 210,
    sellingPrice: 280,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0179",
    name: "PVC fitting and piping 50ml",
    code: "PLP-0004",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0180",
    name: "Contact pipe 100ml",
    code: "PLP-0005",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0181",
    name: "Piping 1 1/4 inch",
    code: "PLP-0006",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 55,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0182",
    name: "Piping 1 1/2 inch",
    code: "PLP-0007",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 18,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0183",
    name: "Piping 2 inch",
    code: "PLP-0008",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0184",
    name: "Flex tube metallic - small",
    code: "PLP-0009",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 13,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0185",
    name: "Flex tube metallic - long",
    code: "PLP-0010",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0186",
    name: "Bottle trap 1 1/2 inch",
    code: "PLP-0011",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 135,
    sellingPrice: 180,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0187",
    name: "Flexible magic connector",
    code: "PLP-0012",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 135,
    sellingPrice: 180,
    stock: 27,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0188",
    name: "Plug",
    code: "PLP-0013",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0189",
    name: "Plug - small",
    code: "PLP-0014",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 17,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0190",
    name: "Plug - medium",
    code: "PLP-0015",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0191",
    name: "Second pile 3/4 inch",
    code: "PLP-0016",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 38,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0192",
    name: "Second pile 1/2 inch",
    code: "PLP-0017",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 32,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0193",
    name: "PVC male connector 3/4 inch",
    code: "PLP-0018",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 17,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0194",
    name: "PVC male connector 1/2 inch",
    code: "PLP-0019",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 15,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0195",
    name: "T-pipe 1/2 inch",
    code: "PLP-0020",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 21,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0196",
    name: "Big bend 1 inch",
    code: "PLP-0021",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0197",
    name: "PVC socket 3/4 inch",
    code: "PLP-0022",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0198",
    name: "PVC socket 1/2 inch",
    code: "PLP-0023",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 15,
    sellingPrice: 20,
    stock: 47,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0199",
    name: "Male tee 1/2 by 1/2",
    code: "PLP-0024",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 56,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0200",
    name: "Female tee 3/4 by 3/4",
    code: "PLP-0025",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0201",
    name: "Male adapter",
    code: "PLP-0026",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0202",
    name: "Male-female tee 3/4 by 1/2",
    code: "PLP-0027",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 20,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0203",
    name: "Female adapter 3/4 by 1/2",
    code: "PLP-0028",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0204",
    name: "Male adapter 3/4 by 1/2",
    code: "PLP-0029",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0205",
    name: "Female elbow 3/4 by 1/2",
    code: "PLP-0030",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 59,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0206",
    name: "Male elbow 3/4 by 1/2",
    code: "PLP-0031",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0207",
    name: "Female adapter 3/4 by 3/4",
    code: "PLP-0032",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 53,
    sellingPrice: 70,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0208",
    name: "Female tee 1/2 by 1/2",
    code: "PLP-0033",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0209",
    name: "Female tee 3/4 by 1/2",
    code: "PLP-0034",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 15,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0210",
    name: "Flexible cable 1/2 by 30",
    code: "PLP-0035",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 60,
    sellingPrice: 80,
    stock: 7,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0211",
    name: "PPR elbow 3/4",
    code: "PLP-0036",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0212",
    name: "PPR tee 3/4",
    code: "PLP-0037",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 49,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0213",
    name: "PPR plain socket 3/4",
    code: "PLP-0038",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 15,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0214",
    name: "Angle valve",
    code: "PLP-0039",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 17,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0215",
    name: "Sink hole",
    code: "PLP-0040",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0216",
    name: "Thread seal tape - small",
    code: "PLP-0041",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 24,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0217",
    name: "Thread seal tape - big",
    code: "PLP-0042",
    category: "Plumbing & Piping",
    description: "",
    supplierId: "s15",
    supplierName: "PipeWorks Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 22,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0218",
    name: "Stainless steel trowel",
    code: "MAH-0001",
    category: "Masonry & Hand Tools",
    description: "",
    supplierId: "s16",
    supplierName: "MasonPro Supplies",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 28,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0219",
    name: "Trowel - juakali",
    code: "MAH-0002",
    category: "Masonry & Hand Tools",
    description: "",
    supplierId: "s16",
    supplierName: "MasonPro Supplies",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0220",
    name: "Trowel - plastic handle",
    code: "MAH-0003",
    category: "Masonry & Hand Tools",
    description: "",
    supplierId: "s16",
    supplierName: "MasonPro Supplies",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0221",
    name: "Tin cutter - big",
    code: "MAH-0004",
    category: "Masonry & Hand Tools",
    description: "",
    supplierId: "s16",
    supplierName: "MasonPro Supplies",
    buyingPrice: 338,
    sellingPrice: 450,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0222",
    name: "Tin cutter - small",
    code: "MAH-0005",
    category: "Masonry & Hand Tools",
    description: "",
    supplierId: "s16",
    supplierName: "MasonPro Supplies",
    buyingPrice: 300,
    sellingPrice: 400,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0223",
    name: "Broom brush (brush only)",
    code: "MAH-0006",
    category: "Masonry & Hand Tools",
    description: "",
    supplierId: "s16",
    supplierName: "MasonPro Supplies",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0224",
    name: "Tapin screw 40mm (pack)",
    code: "FAF-0001",
    category: "Fasteners & Fixings",
    description: "",
    supplierId: "s17",
    supplierName: "FixIt Fasteners",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0225",
    name: "Tapin screw 25mm (pack)",
    code: "FAF-0002",
    category: "Fasteners & Fixings",
    description: "",
    supplierId: "s17",
    supplierName: "FixIt Fasteners",
    buyingPrice: 30,
    sellingPrice: 40,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0226",
    name: "Expand nails with screw (pack)",
    code: "FAF-0003",
    category: "Fasteners & Fixings",
    description: "",
    supplierId: "s17",
    supplierName: "FixIt Fasteners",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0227",
    name: "Gasket maker (RTV silicon)",
    code: "ADS-0001",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 42,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0228",
    name: "GP silicon",
    code: "ADS-0002",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0229",
    name: "Wood glue - type 1",
    code: "ADS-0003",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 6,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0230",
    name: "Wood glue - type 2",
    code: "ADS-0004",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 165,
    sellingPrice: 220,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0231",
    name: "Water proof cement",
    code: "ADS-0005",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 25,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0232",
    name: "Roof sealer - Bodex 200g",
    code: "ADS-0006",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 12,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0233",
    name: "Roof sealer - Bodex 300g",
    code: "ADS-0007",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0234",
    name: "Roof sealer - Bodex 1kg",
    code: "ADS-0008",
    category: "Adhesives & Sealants",
    description: "",
    supplierId: "s18",
    supplierName: "SealRight Chemicals",
    buyingPrice: 188,
    sellingPrice: 250,
    stock: 2,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0235",
    name: "Double curtain rod - without lock",
    code: "HSF-0001",
    category: "Household Fittings",
    description: "",
    supplierId: "s19",
    supplierName: "HomeFix Distributors",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 39,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0236",
    name: "Double curtain rod - with lock",
    code: "HSF-0002",
    category: "Household Fittings",
    description: "",
    supplierId: "s19",
    supplierName: "HomeFix Distributors",
    buyingPrice: 83,
    sellingPrice: 110,
    stock: 16,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0237",
    name: "Door lock - type 1",
    code: "HSF-0003",
    category: "Household Fittings",
    description: "",
    supplierId: "s19",
    supplierName: "HomeFix Distributors",
    buyingPrice: 450,
    sellingPrice: 600,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0238",
    name: "Door lock - type 2",
    code: "HSF-0004",
    category: "Household Fittings",
    description: "",
    supplierId: "s19",
    supplierName: "HomeFix Distributors",
    buyingPrice: 638,
    sellingPrice: 850,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0239",
    name: "Mop head",
    code: "HSF-0005",
    category: "Household Fittings",
    description: "",
    supplierId: "s19",
    supplierName: "HomeFix Distributors",
    buyingPrice: 263,
    sellingPrice: 350,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0240",
    name: "Broom brush (Ksh 450 type)",
    code: "HSF-0006",
    category: "Household Fittings",
    description: "",
    supplierId: "s19",
    supplierName: "HomeFix Distributors",
    buyingPrice: 338,
    sellingPrice: 450,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0241",
    name: "Chicken wire (1m roll)",
    code: "BMC-0001",
    category: "Building Materials & Chemicals",
    description: "",
    supplierId: "s20",
    supplierName: "BuildChem Supplies",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0242",
    name: "Polythene bag (1m roll)",
    code: "BMC-0002",
    category: "Building Materials & Chemicals",
    description: "",
    supplierId: "s20",
    supplierName: "BuildChem Supplies",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0243",
    name: "Battery water chloride oxide",
    code: "BMC-0003",
    category: "Building Materials & Chemicals",
    description: "",
    supplierId: "s20",
    supplierName: "BuildChem Supplies",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0244",
    name: "Shelf bracket 10x12",
    code: "BRH-0001",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 56,
    sellingPrice: 75,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0245",
    name: "Shelf bracket 8x10",
    code: "BRH-0002",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 45,
    sellingPrice: 60,
    stock: 22,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0246",
    name: "Shelf bracket 6x8",
    code: "BRH-0003",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 34,
    sellingPrice: 45,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0247",
    name: "Jua kali hinge - small",
    code: "BRH-0004",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 9,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0248",
    name: "Jua kali hinge - big",
    code: "BRH-0005",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 38,
    sellingPrice: 50,
    stock: 13,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0249",
    name: "Butt hinge 2.5 inch",
    code: "BRH-0006",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 19,
    sellingPrice: 25,
    stock: 26,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0250",
    name: "Butt hinge 2 inch",
    code: "BRH-0007",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 15,
    sellingPrice: 20,
    stock: 72,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0251",
    name: "Steel hinge 4x3 inch",
    code: "BRH-0008",
    category: "Brackets & Hinges",
    description: "",
    supplierId: "s21",
    supplierName: "HingeRight Hardware",
    buyingPrice: 225,
    sellingPrice: 300,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0252",
    name: "Brake shoes",
    code: "MBP-0001",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 20,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0253",
    name: "Bicycle bell (Ksh 200 type)",
    code: "MBP-0002",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0254",
    name: "Bicycle bell (Ksh 150 type)",
    code: "MBP-0003",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 113,
    sellingPrice: 150,
    stock: 4,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0255",
    name: "Turn signal",
    code: "MBP-0004",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0256",
    name: "Motorcycle chain",
    code: "MBP-0005",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 375,
    sellingPrice: 500,
    stock: 3,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0257",
    name: "Patches",
    code: "MBP-0006",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 23,
    sellingPrice: 30,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0258",
    name: "Signal bulb",
    code: "MBP-0007",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 15,
    sellingPrice: 20,
    stock: 11,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0259",
    name: "Bike battery",
    code: "MBP-0008",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 1125,
    sellingPrice: 1500,
    stock: 1,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
  {
    id: "i0260",
    name: "Bearing",
    code: "MBP-0009",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 39,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0261",
    name: "Super tubes",
    code: "MBP-0010",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 210,
    sellingPrice: 280,
    stock: 10,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0262",
    name: "Motorcycle flasher",
    code: "MBP-0011",
    category: "Motorcycle & Bicycle Parts",
    description: "",
    supplierId: "s22",
    supplierName: "AutoBike Parts Kenya",
    buyingPrice: 75,
    sellingPrice: 100,
    stock: 8,
    reorderLevel: 5,
    status: "In Stock",
    image: "",
  },
  {
    id: "i0263",
    name: "Safety goggles",
    code: "SAF-0001",
    category: "Safety Equipment",
    description: "",
    supplierId: "s23",
    supplierName: "SafeGuard PPE",
    buyingPrice: 150,
    sellingPrice: 200,
    stock: 5,
    reorderLevel: 5,
    status: "Low Stock",
    image: "",
  },
];
