services:
  - type: web
    name: hardware-pos-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: hardware-pos-db
          property: connectionString
      - key: JWT_SECRET
        value: d71263dc63ffbd3bea870678dca904437578a279914e067ed41ac1d57f691087
      - key: JWT_REFRESH_SECRET
        value: 6530d415a5e3a30896a9d9252aee36b8a8a21ffb257635dfe63c2647c46cb302
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://temp-frontend-placeholder.example.com

databases:
  - name: hardware-pos-db
    databaseName: hardware
    user: hardware_user
    plan: free
